[phases.setup]
nixPkgs = ["php82", "php82Extensions.sqlite3", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "composer"]

[phases.build]
cmds = ["composer install --no-dev", "touch database/database.sqlite", "php artisan migrate --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"